### PR TITLE
numbers

### PR DESCRIPTION
**Pull request by fnenu**
[Review on Reviewable](https://reviewable-dev-fnenu.firebaseapp.com/reviews/sarahnorell/maths/4)

### CODE REVIEW

**Comment by fnenu** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[1.txt, line 2 [r1]](https://localhost:8080/reviews/sarahnorell/maths/4#-JridvIv4E8p1XrO5kSc)** ([raw file](https://github.com/sarahnorell/maths/blob/6a074d5ad852c4a4f26af9cb76bdbe3b1d8785e9/1.txt#L2)):</sup>
Scale not right compared with the two.

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/sarahnorell/maths/4)

**Comment by fnenu** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[2.txt, line 3 [r2]](https://localhost:8080/reviews/sarahnorell/maths/4#-JrijNmbN3oAKu-Z5Enm)** ([raw file](https://github.com/sarahnorell/maths/blob/11d7e691ecfd0db884e364f173ab96a0881188e0/2.txt#L3)):</sup>
Tea for 2?

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/sarahnorell/maths/4)

**Comment by fnenuwnar** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[1.txt, line 7 [r2]](https://localhost:8080/reviews/sarahnorell/maths/4#-Jry2RcipVCtXI6gRGJX)** ([raw file](https://github.com/sarahnorell/maths/blob/11d7e691ecfd0db884e364f173ab96a0881188e0/1.txt#L7)):</sup>
don't like this

---

<sup>**[2.txt, line 3 [r2]](https://localhost:8080/reviews/sarahnorell/maths/4#-JrijNmbN3oAKu-Z5Enm)** ([raw file](https://github.com/sarahnorell/maths/blob/11d7e691ecfd0db884e364f173ab96a0881188e0/2.txt#L3)):</sup>
hmm maybe

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/sarahnorell/maths/4)

**Comment by fnenuwnar** [comment]
A response

---

Review status: 0 of 2 files reviewed, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/sarahnorell/maths/4)

**Comment by fnenuwnar** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[1.txt, line 3 [r2]](https://reviewable-dev-fnenu.firebaseapp.com:443/reviews/sarahnorell/maths/4#-Jry4OQxJdvwSF8Mi1wN)** ([raw file](https://github.com/sarahnorell/maths/blob/11d7e691ecfd0db884e364f173ab96a0881188e0/1.txt#L3)):</sup>
No.

---

Comments from the [review on Reviewable.io](https://reviewable-dev-fnenu.firebaseapp.com:443/reviews/sarahnorell/maths/4)

**Comment by fnenu** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[1.txt, line 3 [r2]](https://reviewable-dev-fnenu.firebaseapp.com:443/reviews/sarahnorell/maths/4#-Jry4OQxJdvwSF8Mi1wN)** ([raw file](https://github.com/sarahnorell/maths/blob/11d7e691ecfd0db884e364f173ab96a0881188e0/1.txt#L3)):</sup>
Maybe?

---

Comments from the [review on Reviewable.io](https://reviewable-dev-fnenu.firebaseapp.com:443/reviews/sarahnorell/maths/4)

**Comment by fnenuwnar** [comment]
,

---

Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- 1.txt @ r2
- 2.txt @ r1

---

<sup>**[1.txt, line 3 [r2]](https://localhost:8080/reviews/sarahnorell/maths/4#-Jry4OQxJdvwSF8Mi1wN)** ([raw file](https://github.com/sarahnorell/maths/blob/11d7e691ecfd0db884e364f173ab96a0881188e0/1.txt#L3)):</sup>
No.

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/sarahnorell/maths/4)

**Comment by fnenu** [comment]
ok

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://localhost:8080/reviews/sarahnorell/maths/4)

**Pull request merged**
